#
# 服务器 配置
server:
  # 端口
  port: 8321
  servlet:
    # 项目名
    context-path: /Spring-Boot-Sharding-JDBC
  # 用于 Nginx 代理时获取真实 IP
  # 是否应将X-Forwarded-* 标头应用于HttpRequest。
  # use-forward-headers: true 已过时，应使用 forward-headers-strategy 设置为 NATIVE
  # use-forward-headers: true
  forward-headers-strategy: NATIVE
  tomcat:
    # 从中提取远程IP的HTTP标头的名称。 例如，`X-FORWARDED-FOR`。
    remote-ip-header: X-Real-IP
    # 用于覆盖原始端口值的HTTP标头的名称。
    port-header: X-Forwarded-Proto
#
# Spring Boot 配置
spring:
  #
  # Sharding-Jdbc
  shardingsphere:
    # 分表分库 数据源
    datasource:
      # 列出所有数据源
      names: sharding-0,sharding-1,sharding-2,sharding-3,sharding-4,sharding-5,sharding-6,sharding-7,sharding-8,sharding-9
      # 数据库标识与实际数据库名称相同
      sharding-0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.p6spy.engine.spy.P6SpyDriver
        jdbc-url: jdbc:p6spy:mysql://127.0.0.1:3306/sharding-0?useSSL=false&serverTimezone=GMT%2B8
        username: root
        password: root
      sharding-1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.p6spy.engine.spy.P6SpyDriver
        jdbc-url: jdbc:p6spy:mysql://127.0.0.1:3306/sharding-1?useSSL=false&serverTimezone=GMT%2B8
        username: root
        password: root
      sharding-2:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.p6spy.engine.spy.P6SpyDriver
        jdbc-url: jdbc:p6spy:mysql://127.0.0.1:3306/sharding-2?useSSL=false&serverTimezone=GMT%2B8
        username: root
        password: root
      sharding-3:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.p6spy.engine.spy.P6SpyDriver
        jdbc-url: jdbc:p6spy:mysql://127.0.0.1:3306/sharding-3?useSSL=false&serverTimezone=GMT%2B8
        username: root
        password: root
      sharding-4:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.p6spy.engine.spy.P6SpyDriver
        jdbc-url: jdbc:p6spy:mysql://127.0.0.1:3306/sharding-4?useSSL=false&serverTimezone=GMT%2B8
        username: root
        password: root
      sharding-5:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.p6spy.engine.spy.P6SpyDriver
        jdbc-url: jdbc:p6spy:mysql://127.0.0.1:3306/sharding-5?useSSL=false&serverTimezone=GMT%2B8
        username: root
        password: root
      sharding-6:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.p6spy.engine.spy.P6SpyDriver
        jdbc-url: jdbc:p6spy:mysql://127.0.0.1:3306/sharding-6?useSSL=false&serverTimezone=GMT%2B8
        username: root
        password: root
      sharding-7:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.p6spy.engine.spy.P6SpyDriver
        jdbc-url: jdbc:p6spy:mysql://127.0.0.1:3306/sharding-7?useSSL=false&serverTimezone=GMT%2B8
        username: root
        password: root
      sharding-8:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.p6spy.engine.spy.P6SpyDriver
        jdbc-url: jdbc:p6spy:mysql://127.0.0.1:3306/sharding-8?useSSL=false&serverTimezone=GMT%2B8
        username: root
        password: root
      sharding-9:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.p6spy.engine.spy.P6SpyDriver
        jdbc-url: jdbc:p6spy:mysql://127.0.0.1:3306/sharding-9?useSSL=false&serverTimezone=GMT%2B8
        username: root
        password: root
    # 分表分库
    sharding:
      # 表配置
      tables:
        # 表名，测试用户表（分库配置）
        test_user:
          # 表逻辑
          logic-table: test_user
          # 数据库逻辑
          database-strategy:
            # 队列
            inline:
              # 字段
              sharding-column: test_user_id
              # 数据库算法
              algorithm-expression: sharding-${test_user_id % 10}
    # 属性
    props:
      # 显示 SQL
      sql.show: true
#
#  # 数据库 配置
#  datasource:
#    #
#    # 多数据源
#    #
#    # 没有@DS	      默认数据源
#    # @DS("dsName")	  dsName可以为组名也可以为具体某个库的名称
#    # 可以注解在方法上,可以注解在service实现或mapper接口方法上。
#    dynamic:
#      # 设置默认的数据源或者数据源组,默认值即为master,如果你主从默认下主库的名称就是master可不定义此项。
#      primary: master
#      datasource:
#        # 主数据源
#        master:
#          # 驱动（打包时使用）
#          # driver-class-name: com.mysql.cj.jdbc.Driver
#          # URL（打包时使用）
#          # url: jdbc:mysql://127.0.0.1:3306/sharding?useSSL=false&serverTimezone=GMT%2B8
#          #
#          # 测试驱动（非打包时使用）
#          driver-class-name: com.p6spy.engine.spy.P6SpyDriver
#          # 测试 URL（非打包时使用）
#          url: jdbc:p6spy:mysql://127.0.0.1:3306/sharding-1?useSSL=false&serverTimezone=GMT%2B8
#          # 用户名
#          username: root
#          # 密码
#          password: root
#        # 节点 2
#        node_2:
#          driver-class-name: com.p6spy.engine.spy.P6SpyDriver
#          url: jdbc:p6spy:mysql://127.0.0.1:3306/sharding-2?useSSL=false&serverTimezone=GMT%2B8
#          username: root
#          password: root
#    #
#    # Hikari 连接池
#    hikari:
#      # 最小空闲连接数量
#      minimum-idle: 3
#      # 连接池最大连接数
#      maximum-pool-size: 10
#
# MyBatis Plus 配置
mybatis-plus:
  # MyBatis Mapper 所对应的 XML 文件位置，如果您在 Mapper 中有自定义方法（XML 中有自定义实现），需要进行该配置，告诉 Mapper 所对应的 XML 文件位置。
  # 必须配置（否则出现：org.apache.ibatis.binding.BindingException: Invalid bound statement (not found)）
  mapper-locations: classpath:mapper/*.xml
  # MyBaits 别名包扫描路径，通过该属性可以给包中的类注册别名，注册后在 Mapper 对应的 XML 文件中可以直接使用类名，
  # 而不用使用全限定的类名（即 XML 中调用的时候不用包含包名）。
  type-aliases-package: cn.com.xuxiaowei.entity
  # 枚举类 扫描路径，如果配置了该属性，会将路径下的枚举类进行注入，让实体类字段能够简单快捷的使用枚举属性，
  # 具体使用请结合 枚举注入（https://mp.baomidou.com/guide/enum.html） 查看。
  type-enums-package: cn.com.xuxiaowei.entity
  global-config:
    db-config:
      # 逻辑已删除值,(逻辑删除下有效，默认值：1)
      logic-delete-value: 1
      # 逻辑未删除值,(逻辑删除下有效，默认值：0)
      logic-not-delete-value: 0
    # MyBatis 配置
  configuration:
    # 缓存
    cache-enabled: true
#
# 日志 配置
# 使用方法:
# 在类上面使用注解 @Slf4j
# 在类中使用
# log.debug("");
# log.info("");
# log.error("");
logging:
  # 日志文件
  file:
    # 文件名及路径
    name: /log/Spring-Boot-Sharding-JDBC/Spring-Boot-Sharding-JDBC.log
    # 文件最大大小,单位: org.springframework.util.unit.DataSize
    max-size: 20MB
    #日志保存天数
    max-history: 60
  # 格式
  pattern:
    # 压缩文件命名
    rolling-file-name: "${LOG_FILE}.%d{yyyy-MM-dd}.%i.log.gz"
    # 控制台日志格式
    # 默认值: %clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}
    # LOG_LEVEL_PATTERN：日志等级
    # -%5p：宽度
    # PID：线程
    console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %X{NAME} %clr(:){faint} %X{IP} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
    # 日志文件格式
    file: "%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}} ${LOG_LEVEL_PATTERN:-%5p} ${PID:- } --- [%t] %-40.40logger{39} : %X{NAME} : %X{IP} : %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
    # 日期时间格式
    dateformat: "yyyy-MM-dd HH:mm:ss.SSS"
